# Generated by Django 2.2.28 on 2022-06-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220610_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='enquiry_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wedding_date',
            field=models.TextField(),
        ),
    ]
