# Generated by Django 2.2.28 on 2022-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220610_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wedding_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
